include("${CMAKE_CURRENT_LIST_DIR}/rule.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/file.cmake")

set(GeminiRelayDriver_default_library_list )

# Handle files with suffix s, for group default-AVR-GCC
if(GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_assemble)
add_library(GeminiRelayDriver_default_default_AVR_GCC_assemble OBJECT ${GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_assemble})
    GeminiRelayDriver_default_default_AVR_GCC_assemble_rule(GeminiRelayDriver_default_default_AVR_GCC_assemble)
    list(APPEND GeminiRelayDriver_default_library_list "$<TARGET_OBJECTS:GeminiRelayDriver_default_default_AVR_GCC_assemble>")

endif()

# Handle files with suffix S, for group default-AVR-GCC
if(GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_assembleWithPreprocess)
add_library(GeminiRelayDriver_default_default_AVR_GCC_assembleWithPreprocess OBJECT ${GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_assembleWithPreprocess})
    GeminiRelayDriver_default_default_AVR_GCC_assembleWithPreprocess_rule(GeminiRelayDriver_default_default_AVR_GCC_assembleWithPreprocess)
    list(APPEND GeminiRelayDriver_default_library_list "$<TARGET_OBJECTS:GeminiRelayDriver_default_default_AVR_GCC_assembleWithPreprocess>")

endif()

# Handle files with suffix [cC], for group default-AVR-GCC
if(GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_compile)
add_library(GeminiRelayDriver_default_default_AVR_GCC_compile OBJECT ${GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_compile})
    GeminiRelayDriver_default_default_AVR_GCC_compile_rule(GeminiRelayDriver_default_default_AVR_GCC_compile)
    list(APPEND GeminiRelayDriver_default_library_list "$<TARGET_OBJECTS:GeminiRelayDriver_default_default_AVR_GCC_compile>")

endif()

# Handle files with suffix cpp, for group default-AVR-GCC
if(GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_compile_cpp)
add_library(GeminiRelayDriver_default_default_AVR_GCC_compile_cpp OBJECT ${GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_compile_cpp})
    GeminiRelayDriver_default_default_AVR_GCC_compile_cpp_rule(GeminiRelayDriver_default_default_AVR_GCC_compile_cpp)
    list(APPEND GeminiRelayDriver_default_library_list "$<TARGET_OBJECTS:GeminiRelayDriver_default_default_AVR_GCC_compile_cpp>")

endif()

# Handle files with suffix elf, for group default-AVR-GCC
if(GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_objcopy_ihex)
add_library(GeminiRelayDriver_default_default_AVR_GCC_objcopy_ihex OBJECT ${GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_objcopy_ihex})
    GeminiRelayDriver_default_default_AVR_GCC_objcopy_ihex_rule(GeminiRelayDriver_default_default_AVR_GCC_objcopy_ihex)
    list(APPEND GeminiRelayDriver_default_library_list "$<TARGET_OBJECTS:GeminiRelayDriver_default_default_AVR_GCC_objcopy_ihex>")

endif()

# Handle files with suffix elf, for group default-AVR-GCC
if(GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_objcopy_eep)
add_library(GeminiRelayDriver_default_default_AVR_GCC_objcopy_eep OBJECT ${GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_objcopy_eep})
    GeminiRelayDriver_default_default_AVR_GCC_objcopy_eep_rule(GeminiRelayDriver_default_default_AVR_GCC_objcopy_eep)
    list(APPEND GeminiRelayDriver_default_library_list "$<TARGET_OBJECTS:GeminiRelayDriver_default_default_AVR_GCC_objcopy_eep>")

endif()

# Handle files with suffix elf, for group default-AVR-GCC
if(GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_objcopy_lss)
add_library(GeminiRelayDriver_default_default_AVR_GCC_objcopy_lss OBJECT ${GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_objcopy_lss})
    GeminiRelayDriver_default_default_AVR_GCC_objcopy_lss_rule(GeminiRelayDriver_default_default_AVR_GCC_objcopy_lss)
    list(APPEND GeminiRelayDriver_default_library_list "$<TARGET_OBJECTS:GeminiRelayDriver_default_default_AVR_GCC_objcopy_lss>")

endif()

# Handle files with suffix elf, for group default-AVR-GCC
if(GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_objcopy_srec)
add_library(GeminiRelayDriver_default_default_AVR_GCC_objcopy_srec OBJECT ${GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_objcopy_srec})
    GeminiRelayDriver_default_default_AVR_GCC_objcopy_srec_rule(GeminiRelayDriver_default_default_AVR_GCC_objcopy_srec)
    list(APPEND GeminiRelayDriver_default_library_list "$<TARGET_OBJECTS:GeminiRelayDriver_default_default_AVR_GCC_objcopy_srec>")

endif()

# Handle files with suffix elf, for group default-AVR-GCC
if(GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_objcopy_sig)
add_library(GeminiRelayDriver_default_default_AVR_GCC_objcopy_sig OBJECT ${GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_objcopy_sig})
    GeminiRelayDriver_default_default_AVR_GCC_objcopy_sig_rule(GeminiRelayDriver_default_default_AVR_GCC_objcopy_sig)
    list(APPEND GeminiRelayDriver_default_library_list "$<TARGET_OBJECTS:GeminiRelayDriver_default_default_AVR_GCC_objcopy_sig>")

endif()


# Main target for this project
add_executable(GeminiRelayDriver_default_image__fWvdbmM ${GeminiRelayDriver_default_library_list})

set_target_properties(GeminiRelayDriver_default_image__fWvdbmM PROPERTIES
    OUTPUT_NAME "default"
    SUFFIX ".elf"
    ADDITIONAL_CLEAN_FILES "${output_extensions}"
    RUNTIME_OUTPUT_DIRECTORY "${GeminiRelayDriver_default_output_dir}")
target_link_libraries(GeminiRelayDriver_default_image__fWvdbmM PRIVATE ${GeminiRelayDriver_default_default_AVR_GCC_FILE_TYPE_link})

#Add objcopy steps
GeminiRelayDriver_default_objcopy_ihex_rule(GeminiRelayDriver_default_image__fWvdbmM)
GeminiRelayDriver_default_objcopy_eep_rule(GeminiRelayDriver_default_image__fWvdbmM)
GeminiRelayDriver_default_objcopy_lss_rule(GeminiRelayDriver_default_image__fWvdbmM)
GeminiRelayDriver_default_objcopy_srec_rule(GeminiRelayDriver_default_image__fWvdbmM)
GeminiRelayDriver_default_objcopy_sig_rule(GeminiRelayDriver_default_image__fWvdbmM)
# Add the link options from the rule file.
GeminiRelayDriver_default_link_rule( GeminiRelayDriver_default_image__fWvdbmM)


